version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"   # client port
      - "8222:8222"   # monitoring port
    command: ["-js", "-m", "8222"]

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Edge port (S3, etc)
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-locastack.sh:/docker-entrypoint-initaws.d/init-locastack.sh"

  scanner:
    build: .
    container_name: scanner
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats-server:4222
    command: ["/app/main", "-app=scanner"]
    networks:
      - default

  consumer:
    build: .
    container_name: consumer
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats-server:4222
    command: ["/app/main", "-app=consumer"]
    networks:
      - default

networks:
  default:
    name: dev-net